### ISSUE TITLE
missing a license

### ISSUE THREAD

**Issue by arthurvr** [marcobiedermann/search-engine-optimization#15]
This repo misses a license. You could use https://github.com/sindresorhus/awesome#license as inspiration.

**Comment by marcobiedermann** [comment]
@arthurvr Thanks for the suggestion. I've just added a license for this repos. By the way, does every repo need a license?

**Comment by arthurvr** [comment]
@marcobiedermann Depends, but if you're in doubt and are able to add one, just add one.
