### ISSUE TITLE
Update Clickminded link

### ISSUE THREAD

**Issue by marcobiedermann** [marcobiedermann/search-engine-optimization#30]
>  the link to ClickMinded […] is out of date.

https://twitter.com/TommyGriffith/status/1003221068906053632

**Comment by trg2** [comment]
👍 URL is: https://www.clickminded.com

**Comment by trg2** [comment]
Hey @marcobiedermann - is there anything I can do to help get this live?

**Comment by marcobiedermann** [comment]
@trg2 Just fixed it!
